# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kaskada
# email: your-email@example.com
description: >-
  Kaskada is a query engine for event-based data designed to solve the unique challenges of building & operating real-time ML at scale.
url: https://kaskada.io
twitter_username: kaskadainc
github_username:  kaskada-ai

join_slack: https://join.slack.com/t/kaskada-hq/shared_invite/zt-1t1lms085-bqs2jtGO2TYr9kuuam~c9w

collections:
  events:
    output: true
  redirects:
    output: true
      #permalink: /events/:path/

sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass

google_analytics: G-HR9E2E6TG4


pagination:
  enabled: true
  per_page: 9
  permalink: '/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

plugins:
  - jekyll/vite
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate-v2

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - bin
  - config
  - vite.config.ts
  - tmp
  - Procfile.dev
  - Rakefile
  - exe
  - bin
  - package.json
  - package-lock.json
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
