---
# Feel free to add content and custom Front Matter to this file.
# To modify the layout, see https://jekyllrb.com/docs/themes/#overriding-theme-defaults

layout: page
---

## The engine for real-time ML

Kaskada is a query engine for event-based data designed to solve the unique challenges of building & operating real-time ML at scale. 
Kaskada unifies historical and real-time data processing, allowing practitioners to instantly reconstruct the historical results of a query and then deploy the same query as a live materialization without losing historical context.

Kaskada’s unique capabilities are the result of its time-aware query abstractions, a high-performance compute engine, and a configurable execution model supporting bulk and real-time data processing.


== Train Quickly

====
*Native Time Travel.*

Revisit the result of any query at any point in time.
Use the same query languge to define what to compute and to when to compute it.
====

====
*Instant exploration.*

Efficiently compute directly from raw events.
Safely downsample results with input slicing.
====

====
*Temporal joins.*

Compute point-in-time operations between differently-grouped results.
Combine results defined at different times as continuous values.
====


== Deploy Instantly

====
*Unified queries.*

Execute the same query in batch mode over historical data or in incremental mode over real-time streams.
====

====
*It's fast.*

Compute engine implemented in Rust for performance and safety.
Computation is built on Apache Arrow for speedy CPU utilization.
====

====
*Real-time, but with history.*

Transparently bootstrap real-time queries with the full history of raw events.
====
